services:
  test-db:
    image: mysql:8.0
    container_name: library_test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"
    volumes:
      - test-db-data:/var/lib/mysql

volumes:
  test-db-data: